# for ubuntu :
# debian_release: bionic, focal, groovy, hirsute, jammy, noble
# for debian :
# debian_release : bullseye , bookworm , trixie 
# debian archi can be only amd64 or arm64 

[debian]
ubuntu01 ansible_host=192.168.122.176 debian_release=jammy debian_arch=amd64
debian01 ansible_host=192.168.122. debian_release=bookworm debian_arch=amd64